order:
    - U
    - L
    - F
    - R
    - B
    - D
radius: 3
facelet:
    -
        - 840
        - 192
    -
        - 1188
        - 171
    -
        - 1527
        - 165
    -
        - 864
        - 552
    -
        - 1203
        - 543
    -
        - 1542
        - 522
    -
        - 879
        - 888
    -
        - 1218
        - 876
    -
        - 1548
        - 864
